const localizedMap = {
  'add_event': {
    'en': 'Add event',
    'de': 'Ereignis hinzufügen',
    'es': 'Añadir evento',
    'fr': 'Ajouter un évènement',
    'pt': 'Adicionar Evento',
    'it': 'Aggiungi evento',
    'nl': 'Voeg evenement toe',
    'pl': 'Dodaj wydarzenie',
    'ru': 'Добавить событие',
    'ja': 'イベントを追加します',
    'zh': '添加事件',
    'pt_BR': 'Adicionar Evento',
    'bg': 'Добавете събитие',
    'cs': 'Přidat událost',
    'da': 'Tilføj begivenhed',
    'et': 'ADD sündmus',
    'fi': 'Lisää tapahtuma',
    'el': 'Προσθήκη συμβάντος',
    'hu': 'Esemény hozzáadása',
    'lv': 'Pievienot notikumu',
    'lt': 'Pridėkite įvykį',
    'ro': 'Adăugați eveniment',
    'sk': 'Pridať udalosť',
    'sl': 'Dodaj dogodek',
    'sv': 'Lägg till händelse',
    'hi': 'कार्यक्रम जोड़ें',
    'af': 'Voeg gebeurtenis by',
    'sq': 'Shto ngjarje',
    'am': 'ክስተት ያክሉ',
    'ar': 'أضف الحدث',
    'hy': 'Ավելացնել իրադարձություն',
    'az': 'Hadisə əlavə edin',
    'bn': 'ইভেন্ট যুক্ত করুন',
    'eu': 'Gehitu gertaera',
    'be': 'Дадаць падзея',
    'my': 'အဖြစ်အပျက်တစ်ခုကိုထည့်ပါ',
    'ca': 'Afegiu esdeveniment',
    'hr': 'Dodaj događaj',
    'is': 'Bæta við atburði',
    'id': 'Tambahkan acara',
    'kn': 'ಈವೆಂಟ್ ಸೇರಿಸಿ',
    'kk': 'Оқиған қосыңыз',
    'km': 'បន្ថែមព្រឹត្តិការណ៍',
    'ko': '이벤트 추가',
    'ky': 'Окуя кошуу',
    'lo': 'ເພີ່ມເຫດການ',
    'mk': 'Додадете настан',
    'ms': 'Tambah acara',
    'ml': 'ഇവന്റ് ചേർക്കുക',
    'mn': 'Галт нэмэх',
    'ne': 'घटना थप्नुहोस्',
    'no': 'Legg til arrangement',
    'fa': 'افزودن رویداد',
    'pa': 'ਇਵੈਂਟ ਸ਼ਾਮਲ ਕਰੋ',
    'rm': 'Agiuntar eveniment',
    'si': 'සිද්ධිය එක් කරන්න',
    'ta': 'நிகழ்வைச் சேர்க்கவும்',
    'te': 'ఈవెంట్‌ను జోడించండి',
    'th': 'เพิ่มเหตุการณ์',
    'tr': 'Etkinlik ekle',
    'uk': 'Додати подію',
    'ur': 'واقعہ شامل کریں',
    'vi': 'Thêm sự kiện',
    'zu': 'Faka Umcimbi',
    'fil': 'Magdagdag ng kaganapan',
    'gl': 'Engadir evento',
    'ka': 'ღონისძიების დამატება',
    'he': 'הוסף אירוע',
    'sr': 'Додај догађај',
    'gu': 'ઘટના ઉમેરો',
    'sw': 'Ongeza Tukio'
  },
  'edit_event': {
    'en': 'Edit event',
    'de': 'Ereignis bearbeiten',
    'es': 'Evento de edición',
    'fr': 'Modifier l\'événement',
    'pt': 'Evento de edição',
    'it': 'Modifica evento',
    'nl': 'Event bewerken',
    'pl': 'Edytuj wydarzenie',
    'ru': 'Редактировать событие',
    'ja': '編集イベント',
    'zh': '编辑事件',
    'pt_BR': 'Evento de edição',
    'bg': 'Редактиране на събитие',
    'cs': 'Upravit událost',
    'da': 'Rediger begivenhed',
    'et': 'Redigeerimisüritus',
    'fi': 'Muokkaustapahtuma',
    'el': 'Επεξεργασία συμβάντος',
    'hu': 'Esemény szerkesztése',
    'lv': 'Rediģēšanas pasākums',
    'lt': 'Redaguoti įvykį',
    'ro': 'Editați evenimentul',
    'sk': 'Úpravy',
    'sl': 'Uredi dogodek',
    'sv': 'Redigera händelse',
    'hi': 'संपादन कार्यक्रम',
    'af': 'Redigeer gebeurtenis',
    'sq': 'Redakto ngjarjen',
    'am': 'ክስተት አርትዕ',
    'ar': 'تحرير الحدث',
    'hy': 'Խմբագրել իրադարձությունը',
    'az': 'Hadisəni düzəldin',
    'bn': 'ইভেন্ট সম্পাদনা',
    'eu': 'Editatu gertaera',
    'be': 'Рэдагаваць мерапрыемства',
    'my': 'Event ကိုတည်းဖြတ်ပါ',
    'ca': 'Editar esdeveniment',
    'hr': 'Uredi događaj',
    'is': 'Breyta atburði',
    'id': 'Edit Event',
    'kn': 'ಈವೆಂಟ್ ಸಂಪಾದಿಸಿ',
    'kk': 'Оқиғаны өңдеу',
    'km': 'កែសម្រួលព្រឹត្តិការណ៍',
    'ko': '이벤트 편집',
    'ky': 'Окуяны түзөтүү',
    'lo': 'ເຫດການແກ້ໄຂ',
    'mk': 'Уреди настан',
    'ms': 'Edit acara',
    'ml': 'ഇവന്റ് എഡിറ്റുചെയ്യുക',
    'mn': 'Засах үйл явдлыг засах',
    'ne': 'कार्यक्रम सम्पादन गर्नुहोस्',
    'no': 'Rediger hendelse',
    'fa': 'ویرایش رویداد',
    'pa': 'ਸਮਾਪਤੀ',
    'rm': 'Modifitgar occurrenza',
    'si': 'සිද්ධිය සංස්කරණය කරන්න',
    'ta': 'நிகழ்வைத் திருத்து',
    'te': 'ఈవెంట్‌ను సవరించండి',
    'th': 'แก้ไขเหตุการณ์',
    'tr': 'Düzenleme Etkinliği',
    'uk': 'Редагувати подію',
    'ur': 'واقعہ میں ترمیم کریں',
    'vi': 'Chỉnh sửa sự kiện',
    'zu': 'Hlela umcimbi',
    'fil': 'I -edit ang kaganapan',
    'gl': 'Editar evento',
    'ka': 'რედაქტირება ღონისძიება',
    'he': 'ערוך אירוע',
    'sr': 'Уређивање догађаја',
    'gu': 'સંપાદન ઘટના',
    'sw': 'Hariri Tukio'
  },
  'delete': {
    'en': 'Delete',
    'de': 'Löschen',
    'es': 'Borrar',
    'fr': 'Supprimer',
    'pt': 'Excluir',
    'it': 'Eliminare',
    'nl': 'Verwijderen',
    'pl': 'Usuwać',
    'ru': 'Удалить',
    'ja': '消去',
    'zh': '删除',
    'pt_BR': 'Excluir',
    'bg': 'Изтрий',
    'cs': 'Vymazat',
    'da': 'Slet',
    'et': 'Kustutama',
    'fi': 'Poistaa',
    'el': 'Διαγράφω',
    'hu': 'Töröl',
    'lv': 'Dzēst',
    'lt': 'Ištrinti',
    'ro': 'Șterge',
    'sk': 'Vymazať',
    'sl': 'Izbrisati',
    'sv': 'Radera',
    'hi': 'मिटाना',
    'af': 'Verwyder',
    'sq': 'Nxjerr',
    'am': 'ሰርዝ',
    'ar': 'يمسح',
    'hy': 'Ջնջել',
    'az': 'Silmək',
    'bn': 'মুছে ফেলা',
    'eu': 'Ezabatu',
    'be': 'Выдаляць',
    'my': 'ဖျက်',
    'ca': 'Esborrar',
    'hr': 'Izbrisati',
    'is': 'Eyða',
    'id': 'Menghapus',
    'kn': 'ಅಳಿಸು',
    'kk': 'Жою',
    'km': 'របៅបេលរសច',
    'ko': '삭제',
    'ky': 'Жок кылуу',
    'lo': 'ລົບ',
    'mk': 'Избриши',
    'ms': 'Padam',
    'ml': 'ഇല്ലാതാക്കുക',
    'mn': 'Эдгээх',
    'ne': 'मेटाउन',
    'no': 'Slett',
    'fa': 'حذف',
    'pa': 'ਮਿਟਾਓ',
    'rm': 'Stizzar',
    'si': 'මකන්න',
    'ta': 'அழி',
    'te': 'తొలగించు',
    'th': 'ลบ',
    'tr': 'Silmek',
    'uk': 'Видаляти',
    'ur': 'حذف کریں',
    'vi': 'Xóa bỏ',
    'zu': 'Cisha',
    'fil': 'Tanggalin',
    'gl': 'Eliminar',
    'ka': 'წაშლა',
    'he': 'לִמְחוֹק',
    'sr': 'Избрисати',
    'gu': 'કા delી નાખવું',
    'sw': 'Futa'
  },
  'save': {
    'en': 'Save',
    'de': 'Speichern',
    'es': 'Ahorrar',
    'fr': 'Sauvegarder',
    'pt': 'Salvar',
    'it': 'Salva',
    'nl': 'Redden',
    'pl': 'Ratować',
    'ru': 'Сохранять',
    'ja': '保存',
    'zh': '节省',
    'pt_BR': 'Salvar',
    'bg': 'Запазете',
    'cs': 'Uložit',
    'da': 'Gemme',
    'et': 'Kokkuhoid',
    'fi': 'Tallentaa',
    'el': 'Αποθηκεύσετε',
    'hu': 'Megment',
    'lv': 'Ietaupīt',
    'lt': 'Sutaupyti',
    'ro': 'Salvați',
    'sk': 'Uložiť',
    'sl': 'Shrani',
    'sv': 'Spara',
    'hi': 'बचाना',
    'af': 'Red',
    'sq': 'Ruaj',
    'am': 'አስቀምጥ',
    'ar': 'يحفظ',
    'hy': 'Խնայել',
    'az': 'Yadda saxla',
    'bn': 'সংরক্ষণ',
    'eu': 'Aurreztu',
    'be': 'Ашчаджаць',
    'my': 'ကယ်ဆယ်',
    'ca': 'Estalviar',
    'hr': 'Uštedjeti',
    'is': 'Vista',
    'id': 'Menyimpan',
    'kn': 'ಉಳಿಸು',
    'kk': 'Жинау',
    'km': 'សរេង្គាហ',
    'ko': '구하다',
    'ky': 'Сактоо',
    'lo': 'ປະຢັດ',
    'mk': 'Зачувај',
    'ms': 'Simpan',
    'ml': 'രക്ഷിക്കും',
    'mn': 'Аврах',
    'ne': 'बचाउनु',
    'no': 'Lagre',
    'fa': 'صرفه جویی',
    'pa': 'ਸੇਵ',
    'rm': 'Salvează',
    'si': 'සුරකින්න',
    'ta': 'சேமிக்கவும்',
    'te': 'సేవ్',
    'th': 'บันทึก',
    'tr': 'Kaydetmek',
    'uk': 'Заощадити',
    'ur': 'بچت کریں',
    'vi': 'Cứu',
    'zu': 'Hlenga',
    'fil': 'I -save',
    'gl': 'Gardar',
    'ka': 'Გადარჩენა',
    'he': 'להציל',
    'sr': 'сачувати',
    'gu': 'બચત કરવી',
    'sw': 'Kuokoa'
  },
  'event_title': {
    'en': 'Title',
    'de': 'Titel',
    'es': 'Título',
    'fr': 'Titre',
    'pt': 'Título',
    'it': 'Titolo',
    'nl': 'Titel',
    'pl': 'Tytuł',
    'ru': 'Заголовок',
    'ja': 'タイトル',
    'zh': '标题',
    'pt_BR': 'Título',
    'bg': 'Заглавие',
    'cs': 'Titul',
    'da': 'Titel',
    'et': 'Tiitel',
    'fi': 'Otsikko',
    'el': 'Τίτλος',
    'hu': 'Cím',
    'lv': 'Tituls',
    'lt': 'Pavadinimas',
    'ro': 'Titlu',
    'sk': 'Názov',
    'sl': 'Naslov',
    'sv': 'Titel',
    'hi': 'शीर्षक',
    'af': 'Titel',
    'sq': 'Titull',
    'am': 'ርዕስ',
    'ar': 'عنوان',
    'hy': 'Կոչում',
    'az': 'Başlıq',
    'bn': 'শিরোনাম',
    'eu': 'Izenburua',
    'be': 'Загаловак',
    'my': 'ခေါင်းစဥ်',
    'ca': 'Títol',
    'hr': 'Titula',
    'is': 'Titill',
    'id': 'Judul',
    'kn': 'ಶೀರ್ಷಿಕೆ',
    'kk': 'Тақырып',
    'km': 'ចមនងចើង',
    'ko': '제목',
    'ky': 'Аталышы',
    'lo': 'ໃບຕາດິນ',
    'mk': 'Наслов',
    'ms': 'Tajuk',
    'ml': 'തലക്കെട്ട്',
    'mn': 'Гарчиг',
    'ne': 'शीर्षक',
    'no': 'Tittel',
    'fa': 'عنوان',
    'pa': 'ਸਿਰਲੇਖ',
    'rm': 'Titel',
    'si': 'ශීර්ෂය',
    'ta': 'தலைப்பு',
    'te': 'శీర్షిక',
    'th': 'ชื่อ',
    'tr': 'Başlık',
    'uk': 'Титул',
    'ur': 'عنوان',
    'vi': 'Tiêu đề',
    'zu': 'Ibizo',
    'fil': 'Pamagat',
    'gl': 'Título',
    'ka': 'ტიტული',
    'he': 'כותרת',
    'sr': 'Назив',
    'gu': 'હક',
    'sw': 'Kichwa'
  },
  'event_description': {
    'en': 'Description',
    'de': 'Beschreibung',
    'es': 'Descripción',
    'fr': 'Description',
    'pt': 'Descrição',
    'it': 'Descrizione',
    'nl': 'Beschrijving',
    'pl': 'Opis',
    'ru': 'Описание',
    'ja': '説明',
    'zh': '描述',
    'pt_BR': 'Descrição',
    'bg': 'Описание',
    'cs': 'Popis',
    'da': 'Beskrivelse',
    'et': 'Kirjeldus',
    'fi': 'Kuvaus',
    'el': 'Περιγραφή',
    'hu': 'Leírás',
    'lv': 'Apraksts',
    'lt': 'apibūdinimas',
    'ro': 'Descriere',
    'sk': 'Opis',
    'sl': 'Opis',
    'sv': 'Beskrivning',
    'hi': 'विवरण',
    'af': 'Beskrywing',
    'sq': 'Përshkrim',
    'am': 'መግለጫ',
    'ar': 'وصف',
    'hy': 'Նկարագրություն',
    'az': 'Təsvir',
    'bn': 'বর্ণনা',
    'eu': 'Deskribapen',
    'be': 'Апісанне',
    'my': 'ဖေါ်ပြချက်',
    'ca': 'Descripció',
    'hr': 'Opis',
    'is': 'Lýsing',
    'id': 'Keterangan',
    'kn': 'ವಿವರಣೆ',
    'kk': 'Түсіндірме',
    'km': 'ការបិបន៍នា',
    'ko': '설명',
    'ky': 'Сүрөттөө',
    'lo': 'ລາຍລະອຽດ',
    'mk': 'Опис',
    'ms': 'Penerangan',
    'ml': 'വിവരണം',
    'mn': 'Тодорхойлолт / төрөл анги',
    'ne': 'वर्णन',
    'no': 'Beskrivelse',
    'fa': 'شرح',
    'pa': 'ਵੇਰਵਾ',
    'rm': 'Descripziun',
    'si': 'විස්තර',
    'ta': 'விளக்கம்',
    'te': 'వివరణ',
    'th': 'คำอธิบาย',
    'tr': 'Tanım',
    'uk': 'Опис',
    'ur': 'تفصیل',
    'vi': 'Sự miêu tả',
    'zu': 'Ukufanisa',
    'fil': 'Paglalarawan',
    'gl': 'Descrición',
    'ka': 'აღწერილობა',
    'he': 'תיאור',
    'sr': 'Опис',
    'gu': 'વર્ણન',
    'sw': 'Maelezo'
  },
  'all_day': {
    'en': 'All day',
    'de': 'Den ganzen Tag',
    'es': 'Todo el dia',
    'fr': 'Toute la journée',
    'pt': 'Dia todo',
    'it': 'Tutto il giorno',
    'nl': 'De hele dag',
    'pl': 'Cały dzień',
    'ru': 'Весь день',
    'ja': '一日中',
    'zh': '一整天',
    'pt_BR': 'Dia todo',
    'bg': 'Цял ден',
    'cs': 'Celý den',
    'da': 'Hele dagen',
    'et': 'Terve päev',
    'fi': 'Koko päivä',
    'el': 'Ολη μέρα',
    'hu': 'Egész nap',
    'lv': 'Visu dienu',
    'lt': 'Visą dieną',
    'ro': 'Toată ziua',
    'sk': 'Celý deň',
    'sl': 'Ves dan',
    'sv': 'Hela dagen',
    'hi': 'पूरे दिन',
    'af': 'Heeldag',
    'sq': 'Gjithe diten',
    'am': 'ሙሉ ቀን',
    'ar': 'طوال اليوم',
    'hy': 'Ամբողջ օրը',
    'az': 'Bütün gün',
    'bn': 'সারাদিন',
    'eu': 'Egun osoan',
    'be': 'Увесь дзень',
    'my': 'တနေ့လုံး',
    'ca': 'Tot el dia',
    'hr': 'Cijeli dan',
    'is': 'Allan daginn',
    'id': 'Sepanjang hari',
    'kn': 'ಇಡೀ ದಿನ',
    'kk': 'Күні бойы',
    'km': 'ពេញមួយថ្ងៃ',
    'ko': '하루 종일',
    'ky': 'Күн бою',
    'lo': 'ຫມົດ​ມື້',
    'mk': 'Цел ден',
    'ms': 'Sepanjang hari',
    'ml': 'ദിവസം മുഴുവൻ',
    'mn': 'Бүх өдөр',
    'ne': 'दिनभरि',
    'no': 'Hele dagen',
    'fa': 'تمام روز',
    'pa': 'ਸਾਰਾ ਦਿਨ',
    'rm': 'Tut il di',
    'si': 'දවස පුරාම',
    'ta': 'நாள் முழுவதும்',
    'te': 'రోజంతా',
    'th': 'ทั้งวัน',
    'tr': 'Tüm gün',
    'uk': 'Весь день',
    'ur': 'تمام دن',
    'vi': 'Cả ngày',
    'zu': 'Usuku lonke',
    'fil': 'Buong araw',
    'gl': 'Todo o día',
    'ka': 'Მთელი დღე',
    'he': 'כל היום',
    'sr': 'Цео дан',
    'gu': 'બધા દિવસ',
    'sw': 'Siku nzima'
  },
  'calendar': {
    'en': 'Calendar',
    'de': 'Kalender',
    'es': 'Calendario',
    'fr': 'Calendrier',
    'pt': 'Calendário',
    'it': 'Calendario',
    'nl': 'Kalender',
    'pl': 'Kalendarz',
    'ru': 'Календарь',
    'ja': 'カレンダー',
    'zh': '日历',
    'pt_BR': 'Calendário',
    'bg': 'Календар',
    'cs': 'Kalendář',
    'da': 'Kalender',
    'et': 'Kalender',
    'fi': 'Kalenteri',
    'el': 'Ημερολόγιο',
    'hu': 'Naptár',
    'lv': 'Kalendārs',
    'lt': 'Kalendorius',
    'ro': 'Calendar',
    'sk': 'Kalendár',
    'sl': 'Koledar',
    'sv': 'Kalender',
    'hi': 'पंचांग',
    'af': 'Kalender',
    'sq': 'Kalendar',
    'am': 'የቀን መቁጠሪያ',
    'ar': 'تقويم',
    'hy': 'Օրացույց',
    'az': 'Təqvim',
    'bn': 'ক্যালেন্ডার',
    'eu': 'Egutegi',
    'be': 'Каляндар',
    'my': 'ပြက္ခဒိန်',
    'ca': 'Calendari',
    'hr': 'Kalendar',
    'is': 'Dagatal',
    'id': 'Kalender',
    'kn': 'ಕ್ಯಾಲೆಂಡರ್',
    'kk': 'Күнтібзе',
    'km': 'របកតីតិន',
    'ko': '달력',
    'ky': 'Календарь',
    'lo': 'ປະຕິທິນ',
    'mk': 'Календар',
    'ms': 'Kalendar',
    'ml': 'പഞ്ചാംഗം',
    'mn': 'Хуанли',
    'ne': 'पात्रो',
    'no': 'Kalender',
    'fa': 'تقویم',
    'pa': 'ਕੈਲੰਡਰ',
    'rm': 'Calender',
    'si': 'දින දර්ශනය',
    'ta': 'நாட்காட்டி',
    'te': 'క్యాలెండర్',
    'th': 'ปฏิทิน',
    'tr': 'Takvim',
    'uk': 'Календар',
    'ur': 'کیلنڈر',
    'vi': 'Lịch',
    'zu': 'Unsukuzonke',
    'fil': 'Kalendaryo',
    'gl': 'Calendario',
    'ka': 'Კალენდარი',
    'he': 'לוּחַ שָׁנָה',
    'sr': 'Календар',
    'gu': 'ક calલેન્ડર',
    'sw': 'Kalenda'
  },
  'no_calendar': {
    'en': 'No calendar',
    'de': 'Kein Kalender',
    'es': 'Sin calendario',
    'fr': 'Pas de calendrier',
    'pt': 'Sem calendário',
    'it': 'Nessun calendario',
    'nl': 'Geen agenda',
    'pl': 'Brak kalendarza',
    'ru': 'Нет календаря',
    'ja': 'カレンダーなし',
    'zh': '没有日历',
    'pt_BR': 'Sem calendário',
    'bg': 'Без календар',
    'cs': 'Žádný kalendář',
    'da': 'Ingen kalender',
    'et': 'Kalendrit pole',
    'fi': 'Ei kalenteria',
    'el': 'Χωρίς ημερολόγιο',
    'hu': 'Nincs naptár',
    'lv': 'Nav kalendāra',
    'lt': 'Nėra kalendoriaus',
    'ro': 'Fără calendar',
    'sk': 'Žiadny kalendár',
    'sl': 'Brez koledarja',
    'sv': 'Ingen kalender',
    'hi': 'कोई कैलेंडर नहीं',
    'af': 'Geen kalender nie',
    'sq': 'Asnjë kalendar',
    'am': 'የቀን መቁጠሪያ የለም',
    'ar': 'لا تقويم',
    'hy': 'Օրացույց չկա',
    'az': 'Təqvim yoxdur',
    'bn': 'কোন ক্যালেন্ডার নেই',
    'eu': 'Egutegi ez',
    'be': 'Няма календара',
    'my': 'ပြက္ခဒိန်မရှိပါ',
    'ca': 'Sense calendari',
    'hr': 'Nema kalendara',
    'is': 'Ekkert dagatal',
    'id': 'Tidak ada kalender',
    'kn': 'ಕ್ಯಾಲೆಂಡರ್ ಇಲ್ಲ',
    'kk': 'Күнтізбе',
    'km': 'គ្មានប្រតិទិន',
    'ko': '달력 없음',
    'ky': 'Календарь',
    'lo': 'ບໍ່ມີປະຕິທິນ',
    'mk': 'Нема календар',
    'ms': 'Tiada kalendar',
    'ml': 'കലണ്ടർ ഇല്ല',
    'mn': 'Хуанли байхгүй',
    'ne': 'क्यालेन्डर छैन',
    'no': 'Ingen kalender',
    'fa': 'بدون تقویم',
    'pa': 'ਕੋਈ ਕੈਲੰਡਰ ਨਹੀਂ',
    'rm': 'Nagin chalender',
    'si': 'දින දර්ශනයක් නැත',
    'ta': 'காலண்டர் இல்லை',
    'te': 'క్యాలెండర్ లేదు',
    'th': 'ไม่มีปฏิทิน',
    'tr': 'Takvim yok',
    'uk': 'Немає календаря',
    'ur': 'کوئی کیلنڈر نہیں',
    'vi': 'Không có lịch',
    'zu': 'Alikho Ikhalenda',
    'fil': 'Walang kalendaryo',
    'gl': 'Sen calendario',
    'ka': 'კალენდარი არ არის',
    'he': 'אין לוח שנה',
    'sr': 'Нема календара',
    'gu': 'કોઈ કેલેન્ડર',
    'sw': 'Hakuna kalenda'
  },
  'add_reminder': {
    'en': 'Add reminder',
    'de': 'Erinnerung hinzufügen',
    'es': 'Agregar recordatorio',
    'fr': 'Ajouter le rappel',
    'pt': 'Adicione o lembrete',
    'it': 'Aggiungi promemoria',
    'nl': 'Herinnering toevoegen',
    'pl': 'Dodaj przypomnienie',
    'ru': 'Добавить напоминание',
    'ja': 'リマインダーを追加します',
    'zh': '添加提醒',
    'pt_BR': 'Adicione o lembrete',
    'bg': 'Добавете напомняне',
    'cs': 'Přidejte připomenutí',
    'da': 'Tilføj påmindelse',
    'et': 'Lisage meeldetuletus',
    'fi': 'Lisää muistutus',
    'el': 'Προσθέστε υπενθύμιση',
    'hu': 'Adjon hozzá emlékeztetőt',
    'lv': 'Pievienot atgādinājumu',
    'lt': 'Pridėkite priminimą',
    'ro': 'Adăugați memento',
    'sk': 'Pridať pripomenutie',
    'sl': 'Dodaj opomnik',
    'sv': 'Lägg till påminnelse',
    'hi': 'अनुस्मारक जोड़ें',
    'af': 'Voeg herinnering by',
    'sq': 'Shto kujtesë',
    'am': 'አስታዋሽ ጨምር',
    'ar': 'إضافة تذكير',
    'hy': 'Ավելացնել հիշեցում',
    'az': 'Xatırlatma əlavə edin',
    'bn': 'অনুস্মারক যুক্ত করুন',
    'eu': 'Gehitu abisua',
    'be': 'Дадайце напамін',
    'my': 'သတိပေးချက်ထည့်ပါ',
    'ca': 'Afegiu recordatori',
    'hr': 'Dodajte podsjetnik',
    'is': 'Bættu við áminningu',
    'id': 'Tambahkan pengingat',
    'kn': 'ಜ್ಞಾಪನೆಯನ್ನು ಸೇರಿಸಿ',
    'kk': 'Еске салғышты қосыңыз',
    'km': 'បន្ថែមការរំលឹក',
    'ko': '알림을 추가하십시오',
    'ky': 'Эскерткич кошуу',
    'lo': 'ເພີ່ມຄໍາເຕືອນ',
    'mk': 'Додадете потсетник',
    'ms': 'Tambah peringatan',
    'ml': 'ഓർമ്മപ്പെടുത്തൽ ചേർക്കുക',
    'mn': 'Сануулга нэмүүлэх',
    'ne': 'रिमाइन्डर थप्नुहोस्',
    'no': 'Legg til påminnelse',
    'fa': 'یادآوری اضافه کنید',
    'pa': 'ਰੀਮਾਈਂਡਰ ਸ਼ਾਮਲ ਕਰੋ',
    'rm': 'Agiuntar in regurdientsch',
    'si': 'මතක් කිරීම එක් කරන්න',
    'ta': 'நினைவூட்டலைச் சேர்க்கவும்',
    'te': 'రిమైండర్ జోడించండి',
    'th': 'เพิ่มการเตือนความจำ',
    'tr': 'Hatırlatma Ekle',
    'uk': 'Додайте нагадування',
    'ur': 'یاد دہانی شامل کریں',
    'vi': 'Thêm lời nhắc',
    'zu': 'Faka Isikhumbuzi',
    'fil': 'Magdagdag ng paalala',
    'gl': 'Engade recordatorio',
    'ka': 'შეხსენება დაამატე',
    'he': 'הוסף תזכורת',
    'sr': 'Додати подсетник',
    'gu': 'રીમાઇન્ડર ઉમેરો',
    'sw': 'Ongeza ukumbusho'
  },
  'custom_reminder': {
    'en': 'Custom reminder',
    'de': 'Benutzerdefinierte Erinnerung',
    'es': 'Recordatorio personalizado',
    'fr': 'Rappel personnalisé',
    'pt': 'Lembrete personalizado',
    'it': 'Promemorio personalizzato',
    'nl': 'Aangepaste herinnering',
    'pl': 'Niestandardowe przypomnienie',
    'ru': 'Пользовательское напоминание',
    'ja': 'カスタムリマインダー',
    'zh': '自定义提醒',
    'pt_BR': 'Lembrete personalizado',
    'bg': 'Персонализирано напомняне',
    'cs': 'Vlastní připomenutí',
    'da': 'Brugerdefineret påmindelse',
    'et': 'Kohandatud meeldetuletus',
    'fi': 'Räätälöity muistutus',
    'el': 'Προσαρμοσμένη υπενθύμιση',
    'hu': 'Egyedi emlékeztető',
    'lv': 'Pielāgots atgādinājums',
    'lt': 'Pasirinktinis priminimas',
    'ro': 'Memento personalizat',
    'sk': 'Vlastná pripomienka',
    'sl': 'Opomnik po meri',
    'sv': 'Anpassad påminnelse',
    'hi': 'कस्टम रिमाइंडर',
    'af': 'Pasgemaakte herinnering',
    'sq': 'Kujtesë me porosi',
    'am': 'ብጁ አስታዋሽ',
    'ar': 'تذكير مخصص',
    'hy': 'Պատվերով հիշեցում',
    'az': 'Xüsusi xatırlatma',
    'bn': 'কাস্টম অনুস্মারক',
    'eu': 'Ohiko oroigarria',
    'be': 'Карыстальніцкі напамін',
    'my': 'စိတ်ကြိုက်သတိပေးချက်',
    'ca': 'Recordatori personalitzat',
    'hr': 'Prilagođeni podsjetnik',
    'is': 'Sérsniðin áminning',
    'id': 'Pengingat khusus',
    'kn': 'ಕಸ್ಟಮ್ ಜ್ಞಾಪನೆ',
    'kk': 'Реттелетін еске салу',
    'km': 'ការរំលឹកផ្ទាល់ខ្លួន',
    'ko': '사용자 정의 알림',
    'ky': 'Ыңгайлаштырылган эскертүү',
    'lo': 'ຄໍາເຕືອນທີ່ກໍານົດເອງ',
    'mk': 'Прилагодено потсетување',
    'ms': 'Peringatan tersuai',
    'ml': 'ഇഷ്ടാനുസൃത ഓർമ്മപ്പെടുത്തൽ',
    'mn': 'Хэрэглэгчийн сануулга',
    'ne': 'चलन रिमाइन्डर',
    'no': 'Tilpasset påminnelse',
    'fa': 'یادآوری سفارشی',
    'pa': 'ਕਸਟਮ ਰੀਮਾਈਂਡਰ',
    'rm': 'Promemoria persunalisà',
    'si': 'අභිරුචි මතක් කිරීම',
    'ta': 'தனிப்பயன் நினைவூட்டல்',
    'te': 'అనుకూల రిమైండర్',
    'th': 'การแจ้งเตือนแบบกำหนดเอง',
    'tr': 'Özel Hatırlatma',
    'uk': 'Спеціальне нагадування',
    'ur': 'اپنی مرضی کے مطابق یاد دہانی',
    'vi': 'Nhắc nhở tùy chỉnh',
    'zu': 'Isikhumbuzi Sangokwezifiso',
    'fil': 'Pasadyang paalala',
    'gl': 'Recordatorio personalizado',
    'ka': 'პერსონალური შეხსენება',
    'he': 'תזכורת מותאמת אישית',
    'sr': 'Прилагођени подсетник',
    'gu': 'ક customદા રીમાઇન્ડર',
    'sw': 'Ukumbusho wa kawaida'
  },
  'n_before': {
    'en': '%s before',
    'de': '%s vor',
    'es': '%s antes',
    'fr': '% s avant',
    'pt': '%s antes',
    'it': '%S prima',
    'nl': '%s eerder',
    'pl': '%s wcześniej',
    'ru': '%s до',
    'ja': '％s前',
    'zh': '％s之前',
    'pt_BR': '%s antes',
    'bg': '%s преди',
    'cs': '%s dříve',
    'da': '%s før',
    'et': '%s enne',
    'fi': '%s ennen',
    'el': '%s πριν',
    'hu': '%s korábban',
    'lv': '%s pirms tam',
    'lt': '%s prieš',
    'ro': '%s înainte',
    'sk': '%s predtým',
    'sl': '%s prej',
    'sv': '%s före',
    'hi': 'पहले %s',
    'af': '%S voorheen',
    'sq': '%s më parë',
    'am': '% s ከዚህ በፊት',
    'ar': '٪ s من قبل',
    'hy': '% s առաջ',
    'az': '% s əvvəl',
    'bn': '%এর আগে',
    'eu': '% s aurretik',
    'be': '%s раней',
    'my': '% s မတိုင်မီ',
    'ca': '%s abans',
    'hr': '%s prije',
    'is': '%s áður',
    'id': '%s sebelumnya',
    'kn': '%s ಮೊದಲು',
    'kk': '% s дейін',
    'km': '% s មុនពេល',
    'ko': '이전의 %s',
    'ky': '% s мурун',
    'lo': '% s ກ່ອນ',
    'mk': '%s порано',
    'ms': '%s sebelum ini',
    'ml': '% മുമ്പ്',
    'mn': '% -ийн өмнө',
    'ne': '% s पहिले',
    'no': '%s før',
    'fa': '٪ قبل',
    'pa': '% s ਪਹਿਲਾਂ',
    'rm': '%s avant',
    'si': 'පෙර% s',
    'ta': 'முன் %கள்',
    'te': 'ముందు %s',
    'th': '%s ก่อน',
    'tr': 'Önceden %s',
    'uk': '%s раніше',
    'ur': 'اس سے پہلے ٪ s',
    'vi': '%s trước',
    'zu': '% s ngaphambili',
    'fil': '%s dati',
    'gl': '%s antes',
    'ka': 'ადრე s',
    'he': '%s לפני כן',
    'sr': '% с пре',
    'gu': 'પહેલાં %ઓ',
    'sw': '%s kabla'
  },
  'n_minutes': {
    'en': '%d minutes',
    'de': '%d Minuten',
    'es': '%d minutos',
    'fr': '%d minutes',
    'pt': '%d minutos',
    'it': '%d minuti',
    'nl': '%d minuten',
    'pl': '%d minut',
    'ru': '%d минут',
    'ja': '%d分',
    'zh': '%d分钟',
    'pt_BR': '%d minutos',
    'bg': '%d минути',
    'cs': '%d minut',
    'da': '%d minutter',
    'et': '%d minutit',
    'fi': '%d minuuttia',
    'el': '%d λεπτά',
    'hu': '%d perc',
    'lv': '%d minūtes',
    'lt': '%d minučių',
    'ro': '%d minute',
    'sk': '%d minút',
    'sl': '%d minut',
    'sv': '%d minuter',
    'hi': '%d मिनट',
    'af': '%d minute',
    'sq': '%d minuta',
    'am': '%d ደቂቃዎች',
    'ar': '%d دقيقة',
    'hy': '%d րոպե',
    'az': '%d dəqiqə',
    'bn': '%d মিনিট',
    'eu': '%d minutu',
    'be': '%d хвілін',
    'my': '%d မိနစ်',
    'ca': '%d minuts',
    'hr': '%d minuta',
    'is': '%d mínútur',
    'id': '%d menit',
    'kn': '%d ನಿಮಿಷಗಳು',
    'kk': '%d минут',
    'km': '%d នាទី',
    'ko': '%d 분',
    'ky': '%d мүнөт',
    'lo': 'ສາມນາທີ',
    'mk': '%d минути',
    'ms': '%d minit',
    'ml': '%d മിനിറ്റ്',
    'mn': '%d минут',
    'ne': '%d मिनेट',
    'no': '%d minutter',
    'fa': '%d دقیقه',
    'pa': '%d ਮਿੰਟ',
    'rm': '%d minutas',
    'si': 'මිනිත්තු %d යි',
    'ta': '%d நிமிடங்கள்',
    'te': '%d నిమిషాలు',
    'th': '%d นาที',
    'tr': '%d dakika',
    'uk': '%d хвилин',
    'ur': '%d منٹ',
    'vi': '%d phút',
    'zu': 'Imizuzu engu-%d',
    'fil': '%d minuto',
    'gl': '%d minutos',
    'ka': '%d წუთი',
    'he': '%d דקות',
    'sr': '%d минута',
    'gu': '%d મિનિટ',
    'sw': 'Dakika %d'
  },
  'n_hours': {
    'en': '%d hours',
    'de': '%d Stunden',
    'es': '%d horas',
    'fr': '%d heures',
    'pt': '%d horas',
    'it': '%d ore',
    'nl': '%d uren',
    'pl': '%d godzin',
    'ru': '%d часов',
    'ja': '%d時間',
    'zh': '%d小时',
    'pt_BR': '%d horas',
    'bg': '%d часа',
    'cs': '%d hodin',
    'da': '%d timer',
    'et': '%d tundi',
    'fi': '%d tuntia',
    'el': '%d ΩΡΕΣ',
    'hu': '%d óra',
    'lv': '%d stundas',
    'lt': '%d valandų',
    'ro': '%d ore',
    'sk': '%d hodín',
    'sl': '%d ur',
    'sv': '%d timmar',
    'hi': '%d घंटे',
    'af': '%d uur',
    'sq': '%d ore',
    'am': '%d ሰዓታት',
    'ar': '%d ساعة',
    'hy': '%d ժամ',
    'az': '%d saat',
    'bn': '1 ২ ঘণ্টা',
    'eu': '%d ordu',
    'be': '%d гадзін',
    'my': '%d နာရီ',
    'ca': '%d hores',
    'hr': '%d sati',
    'is': '%d klukkustundir',
    'id': '%d jam',
    'kn': '%d ಗಂಟೆಗಳು',
    'kk': '%d сағат',
    'km': '%d ម៉ោង',
    'ko': '%d 시간',
    'ky': '%d саат',
    'lo': '%d ຊົ່ວໂມງ',
    'mk': '%d часа',
    'ms': '%d jam',
    'ml': '%d മണിക്കൂർ',
    'mn': '%d цаг',
    'ne': '%d घण्टा',
    'no': '%d timer',
    'fa': '%d ساعت',
    'pa': '%d ਘੰਟੇ',
    'rm': '%d uras',
    'si': 'පැය %d යි',
    'ta': '%d மணி நேரம்',
    'te': '%d గంటలు',
    'th': '%d ชั่วโมง',
    'tr': '%d saat',
    'uk': '%d годин',
    'ur': '%d گھنٹے',
    'vi': '%d giờ',
    'zu': '%d amahora',
    'fil': '%d oras',
    'gl': '%d horas',
    'ka': '%d საათი',
    'he': '%d שעות',
    'sr': '%d сати',
    'gu': '%d કલાક',
    'sw': 'Masaa %d'
  },
  'n_days': {
    'en': '%d days',
    'de': '%d Tage',
    'es': '%d días',
    'fr': '%d jours',
    'pt': '%d dias',
    'it': '%d giorni',
    'nl': '%d dagen',
    'pl': '%d dni',
    'ru': '%d дней',
    'ja': '%d日',
    'zh': '%d天',
    'pt_BR': '%d dias',
    'bg': '%d дни',
    'cs': '%d dní',
    'da': '%d dage',
    'et': '%d päeva',
    'fi': '%d päivää',
    'el': '%d ημέρες',
    'hu': '%d nap',
    'lv': '%d dienas',
    'lt': '%d dienų',
    'ro': '%d zile',
    'sk': '%d dní',
    'sl': '%d dni',
    'sv': '%d dagar',
    'hi': 'बारह दिन',
    'af': '%d dae',
    'sq': '%d ditë',
    'am': '%d ቀናት',
    'ar': '%d يوما',
    'hy': '%d օր',
    'az': '%d gün',
    'bn': '%d দিন',
    'eu': '%d egun',
    'be': '%d дзён',
    'my': '%d ရက်',
    'ca': '%d dies',
    'hr': '%d dana',
    'is': '%d dagar',
    'id': '%d hari',
    'kn': '%d ದಿನಗಳು',
    'kk': '%d күн',
    'km': '%d ថ្ងៃ',
    'ko': '%d 일',
    'ky': '%d күн',
    'lo': '%d ວັນ',
    'mk': '%d дена',
    'ms': '%d hari',
    'ml': '%d ദിവസം',
    'mn': '%d өдрүүд',
    'ne': '%d दिन',
    'no': '%d dager',
    'fa': '%d روز',
    'pa': '%d ਦਿਨ',
    'rm': '%d dis',
    'si': 'දින %d යි',
    'ta': '%d நாட்கள்',
    'te': '%d రోజులు',
    'th': '%d วัน',
    'tr': '%d gün',
    'uk': '%d днів',
    'ur': '%d دن',
    'vi': '%d ngày',
    'zu': 'Izinsuku eziyi-%d',
    'fil': '%d araw',
    'gl': '%d días',
    'ka': '%d დღე',
    'he': '%d ימים',
    'sr': '%d дана',
    'gu': '%d દિવસ',
    'sw': 'Siku %d'
  },
  'n_weeks': {
    'en': '%d weeks',
    'de': '%d Wochen',
    'es': '%d semanas',
    'fr': '%d semaines',
    'pt': '%d semanas',
    'it': '%d settimane',
    'nl': '%d weken',
    'pl': '%d tygodni',
    'ru': '%d недель',
    'ja': '%d週間',
    'zh': '%d周',
    'pt_BR': '%d semanas',
    'bg': '%d седмици',
    'cs': '%d týdnů',
    'da': '%d uger',
    'et': '%d nädalat',
    'fi': '%d viikkoa',
    'el': '%d εβδομάδες',
    'hu': '%d hét',
    'lv': '%d nedēļas',
    'lt': '%d savaičių',
    'ro': '%d săptămâni',
    'sk': '%d týždňov',
    'sl': '%d tednov',
    'sv': '%d veckor',
    'hi': '%d सप्ताह',
    'af': '%d weke',
    'sq': '%d javë',
    'am': '%d ሳምንታት',
    'ar': '%d أسبوعا',
    'hy': '%d շաբաթ',
    'az': '%d həftə',
    'bn': '%d সপ্তাহ',
    'eu': '%d aste',
    'be': '%d тыдняў',
    'my': '%d ပတ်',
    'ca': '%d setmanes',
    'hr': '%d tjedana',
    'is': '%d vikur',
    'id': '%d minggu',
    'kn': '%d ವಾರಗಳು',
    'kk': '%d апта',
    'km': '%d សប្តាហ៍',
    'ko': '%d 주',
    'ky': '%d жума',
    'lo': 'ສາມອາທິດ',
    'mk': '%d недели',
    'ms': '%d minggu',
    'ml': '%d ആഴ്ച',
    'mn': '%d долоо хоног',
    'ne': '%d हप्ता',
    'no': '%d uker',
    'fa': '%d هفته',
    'pa': '%d ਹਫ਼ਤੇ',
    'rm': '%d emnas',
    'si': 'සති %d යි',
    'ta': '%d வாரங்கள்',
    'te': '%d వారాలు',
    'th': '%d สัปดาห์',
    'tr': '%d hafta',
    'uk': '%d тижнів',
    'ur': '%d ہفتے',
    'vi': '%d tuần',
    'zu': 'Amaviki ayi-%d',
    'fil': '%d linggo',
    'gl': '%d semanas',
    'ka': '%d კვირა',
    'he': '%d שבועות',
    'sr': '%d недеља',
    'gu': '%d અઠવાડિયા',
    'sw': 'Wiki %d'
  },
  'confirm': {
    'en': 'Confirm',
    'de': 'Bestätigen',
    'es': 'Confirmar',
    'fr': 'Confirmer',
    'pt': 'confirme',
    'it': 'Confermare',
    'nl': 'Bevestigen',
    'pl': 'Potwierdzać',
    'ru': 'Подтверждать',
    'ja': '確認する',
    'zh': '确认',
    'pt_BR': 'confirme',
    'bg': 'Потвърдете',
    'cs': 'Potvrdit',
    'da': 'Bekræfte',
    'et': 'Kinnitama',
    'fi': 'Vahvistaa',
    'el': 'Επιβεβαιώνω',
    'hu': 'megerősít',
    'lv': 'Apstiprināt',
    'lt': 'Patvirtinti',
    'ro': 'A confirma',
    'sk': 'Potvrdiť',
    'sl': 'Potrdite',
    'sv': 'Bekräfta',
    'hi': 'पुष्टि करना',
    'af': 'Bevestig',
    'sq': 'Konfirmoj',
    'am': 'አረጋግጥ',
    'ar': 'يتأكد',
    'hy': 'Հաստատել',
    'az': 'Təsdiq etmək',
    'bn': 'নিশ্চিত করুন',
    'eu': 'Berretsi',
    'be': 'Пацвярджаць',
    'my': 'အတည်ပြု',
    'ca': 'Confirmar',
    'hr': 'Potvrditi',
    'is': 'Staðfesta',
    'id': 'Mengonfirmasi',
    'kn': 'ದೃ confirmಿಸು',
    'kk': 'Растау',
    'km': 'បហ្ជាក់',
    'ko': '확인하다',
    'ky': 'Ыраста',
    'lo': 'ຢືນຢັນ',
    'mk': 'Потврди',
    'ms': 'Mengesahkan',
    'ml': 'ഉറപ്പിക്കുക',
    'mn': 'Батлах',
    'ne': 'पक्का गर्नु',
    'no': 'Bekrefte',
    'fa': 'تایید',
    'pa': 'ਪੁਸ਼ਟੀ ਕਰੋ',
    'rm': 'Confirmar',
    'si': 'තහවුරු කරන්න',
    'ta': 'உறுதிப்படுத்தவும்',
    'te': 'నిర్ధారించండి',
    'th': 'ยืนยัน',
    'tr': 'Onaylamak',
    'uk': 'Підтверджувати',
    'ur': 'تصدیق کریں',
    'vi': 'Xác nhận',
    'zu': 'Gcizelela',
    'fil': 'Kumpirmahin',
    'gl': 'Confirme',
    'ka': 'დადასტურება',
    'he': 'לְאַשֵׁר',
    'sr': 'Потврди',
    'gu': 'પુષ્ટિ આપવી',
    'sw': 'Thibitisha'
  },
  'event_saved': {
    'en': 'Event saved',
    'de': 'Ereignis gespeichert',
    'es': 'Evento guardado',
    'fr': 'Événement enregistré',
    'pt': 'Evento salvo',
    'it': 'Evento salvato',
    'nl': 'Evenement opgeslagen',
    'pl': 'Zatrzymane wydarzenie',
    'ru': 'Событие спасено',
    'ja': 'イベントが保存されました',
    'zh': '事件保存',
    'pt_BR': 'Evento salvo',
    'bg': 'Запазено събитие',
    'cs': 'Uložená událost',
    'da': 'Begivenhed gemt',
    'et': 'Üritus salvestati',
    'fi': 'Tapahtuma tallennettu',
    'el': 'Αποθηκευμένος εκδήλωση',
    'hu': 'Esemény mentve',
    'lv': 'Pasākums saglabāts',
    'lt': 'Išsaugotas įvykis',
    'ro': 'Eveniment salvat',
    'sk': 'Uložená udalosť',
    'sl': 'Dogodek shranjen',
    'sv': 'Händelse sparad',
    'hi': 'इवेंट सेव्ड',
    'af': 'Gebeurtenis gestoor',
    'sq': 'Ngjarja e ruajtur',
    'am': 'ክስተት የተቀመጠ',
    'ar': 'تم حفظ الحدث',
    'hy': 'Միջոցառումը պահպանվեց',
    'az': 'Hadisə qeyd edildi',
    'bn': 'ইভেন্ট সংরক্ষণ',
    'eu': 'Gertaera gorde da',
    'be': 'Падзея захавана',
    'my': 'ဖြစ်ရပ်ကယ်တင်ခြင်းသို့ရောက်ရ၏',
    'ca': 'Esdeveniment estalviat',
    'hr': 'Spremljen događaj',
    'is': 'Atburður vistaður',
    'id': 'Acara disimpan',
    'kn': 'ಈವೆಂಟ್ ಉಳಿಸಲಾಗಿದೆ',
    'kk': 'Оқиға сақталды',
    'km': 'បានរក្សាទុកព្រឹត្តិការណ៍ដែលបានរក្សាទុក',
    'ko': '이벤트 저장',
    'ky': 'Окуя сакталды',
    'lo': 'ເຫດການທີ່ບັນທຶກໄວ້',
    'mk': 'Зачуван настан',
    'ms': 'Acara disimpan',
    'ml': 'ഇവന്റ് സംരക്ഷിച്ചു',
    'mn': 'Үйл явдал хадгалсан',
    'ne': 'घटना बचत भयो',
    'no': 'Arrangementet lagret',
    'fa': 'رویداد ذخیره شد',
    'pa': 'ਇਵੈਂਟ ਦੀ ਬਚਤ',
    'rm': 'Occurrenza memorisada',
    'si': 'සිද්ධිය ඉතිරි විය',
    'ta': 'நிகழ்வு சேமிக்கப்பட்டது',
    'te': 'ఈవెంట్ సేవ్ చేయబడింది',
    'th': 'บันทึกเหตุการณ์',
    'tr': 'Etkinlik Kaydedildi',
    'uk': 'Збережено подію',
    'ur': 'واقعہ محفوظ ہوگیا',
    'vi': 'Sự kiện được lưu',
    'zu': 'Umcimbi ugciniwe',
    'fil': 'Nai -save ang kaganapan',
    'gl': 'Evento gardado',
    'ka': 'შენახული მოვლენა',
    'he': 'אירוע נשמר',
    'sr': 'Догађај сачуван',
    'gu': 'ઘટના બચાવી',
    'sw': 'Tukio limeokolewa'
  },
  'close': {
    'en': 'Close',
    'de': 'Schließen',
    'es': 'Cerca',
    'fr': 'Fermer',
    'pt': 'Fechar',
    'it': 'Vicino',
    'nl': 'Dichtbij',
    'pl': 'Zamknąć',
    'ru': 'Закрывать',
    'ja': '近い',
    'zh': '关闭',
    'pt_BR': 'Fechar',
    'bg': 'Близо',
    'cs': 'Zavřít',
    'da': 'Tæt',
    'et': 'Sulge',
    'fi': 'kiinni',
    'el': 'Κλείσε',
    'hu': 'Bezárás',
    'lv': 'Tuvs',
    'lt': 'Uždaryti',
    'ro': 'Închide',
    'sk': 'Zavrieť',
    'sl': 'Blizu',
    'sv': 'Stänga',
    'hi': 'बंद करना',
    'af': 'Naby',
    'sq': 'I afërt',
    'am': 'ገጠመ',
    'ar': 'يغلق',
    'hy': 'փակել',
    'az': 'Yaxın',
    'bn': 'বন্ধ',
    'eu': 'Hurbileko',
    'be': 'Блізкі',
    'my': 'ပိတ်ထားသော',
    'ca': 'Tanca',
    'hr': 'Zatvoriti',
    'is': 'Lokaðu',
    'id': 'Menutup',
    'kn': 'ಮುಚ್ಚಿಡು',
    'kk': 'Жабық',
    'km': 'បិត',
    'ko': '닫다',
    'ky': 'Жабуу',
    'lo': 'ປິດ',
    'mk': 'Затвори',
    'ms': 'Tutup',
    'ml': 'അടയ്ക്കുക',
    'mn': 'Ойр дөхөм',
    'ne': 'घनिष्ट',
    'no': 'Lukk',
    'fa': 'بستن',
    'pa': 'ਨੇੜੇ',
    'rm': 'Apropiar',
    'si': 'වසන්න',
    'ta': 'நெருக்கமான',
    'te': 'దగ్గరగా',
    'th': 'ปิด',
    'tr': 'Kapalı',
    'uk': 'Закривати',
    'ur': 'بند کریں',
    'vi': 'Đóng',
    'zu': 'Ngokuminyanisa',
    'fil': 'Malapit',
    'gl': 'Pechar',
    'ka': 'ახლო',
    'he': 'סגור',
    'sr': 'Близу',
    'gu': 'બંધ',
    'sw': 'Karibu'
  },
};
