name: edit_calendar_event_view
description: Opens native edit calendar event view
version: 0.3.2+32
repository: https://github.com/chris-wolf/edit_calendar_event_view


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  collection: ^1.18.0
  device_calendar: ^4.3.3
  flutter:
    sdk: flutter
  flutter_timezone: ^4.1.1
  intl: ^0.19.0
  macos_ui: ^2.0.5
  plugin_platform_interface: ^2.0.2
  sprintf: ^7.0.0
  timezone: ^0.9.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: dev.cwolf.editCalendarEventView.edit_calendar_event_view
        pluginClass: EditCalendarEventViewPlugin
      ios:
        pluginClass: EditCalendarEventViewPlugin

screenshots:
  - description: 'Edit event view for iOS'
    path: example/screenshots/edit_calendar_event_view_ios_screenshot.png
